//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_image
    {
        public int C_id { get; set; }
        public Nullable<int> C_index { get; set; }
        public string C_image { get; set; }
        public Nullable<int> C_product_id { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
