//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_product_image = new HashSet<tbl_product_image>();
        }
    
        public int C_id { get; set; }
        public string C_name { get; set; }
        public Nullable<int> C_active { get; set; }
        public string C_description { get; set; }
        public string C_image { get; set; }
        public Nullable<decimal> C_price { get; set; }
        public Nullable<int> C_quantity { get; set; }
        public Nullable<int> C_type { get; set; }
        public Nullable<int> C_category_id { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_product_image> tbl_product_image { get; set; }
    }
}
