//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_detail
    {
        public int C_id { get; set; }
        public Nullable<decimal> C_price { get; set; }
        public Nullable<int> C_quantity { get; set; }
        public Nullable<int> C_order_id { get; set; }
        public Nullable<int> C_product_id { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
    }
}
