//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int C_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> payment_method_id { get; set; }
        public string transaction_id { get; set; }
        public string vnpay_txn_ref { get; set; }
        public string vnpay_bank_code { get; set; }
        public string vnpay_card_type { get; set; }
        public Nullable<System.DateTime> vnpay_pay_date { get; set; }
        public string vnpay_response_code { get; set; }
        public string payment_status { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string raw_request { get; set; }
        public string raw_response { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_payment_method tbl_payment_method { get; set; }
    }
}
