//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_order_detail = new HashSet<tbl_order_detail>();
            this.tbl_payment = new HashSet<tbl_payment>();
        }
    
        public int C_id { get; set; }
        public Nullable<System.DateTime> C_date { get; set; }
        public Nullable<int> C_active { get; set; }
        public Nullable<int> C_member_id { get; set; }
        public Nullable<decimal> C_totalPrice { get; set; }
        public Nullable<int> C_payment_method_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_detail> tbl_order_detail { get; set; }
        public virtual tbl_payment_method tbl_payment_method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_payment> tbl_payment { get; set; }
    }
}
