//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_member()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_member_address = new HashSet<tbl_member_address>();
        }
    
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string C_password { get; set; }
        public string C_email { get; set; }
        public string C_address { get; set; }
        public string C_phone { get; set; }
        public Nullable<int> C_role { get; set; }
        public Nullable<int> C_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_member_address> tbl_member_address { get; set; }
    }
}
