//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_address
    {
        public int C_id { get; set; }
        public string C_name { get; set; }
        public Nullable<int> C_member_id { get; set; }
    
        public virtual tbl_member tbl_member { get; set; }
    }
}
